# Generated by Django 5.0.3 on 2024-03-14 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_token_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="token",
            table="users_tokens",
        ),
    ]
